image: python:3.8

stages:
- test-lost_ds
- release-lost_ds

test-lost_ds:
  stage: test-lost_ds
  script:
    - echo "hello from teststage"
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /master/'
    - if: '$CI_COMMIT_TAG =~ /.*/'

release-lost_ds:
  variables:
    UV_PUBLISH_TOKEN: $TWINE_PASSWORD
  stage: release-lost_ds
  script:
    - sed -i 's/version = "0.0.0-alpha.0"/version = "'"$CI_COMMIT_TAG"'"/' pyproject.toml
    - echo "__version__='${CI_COMMIT_TAG}'" >> lost_ds/__init__.py
    - pip install uv
    - uvx --from=toml-cli toml set --toml-path pyproject.toml project.version ${CI_COMMIT_TAG}
    - uv build
    - uv publish
  only:
    - tags
