image: python:3.8

stages:
- test-lost_ds
- release-lost_ds

variables:
  LOST_DS_VERSION: $CI_PIPELINE_ID
  
test-lost_ds:
  stage: test-lost_ds
  script:
    - echo "hello from teststage"
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /master/'
    - if: '$CI_COMMIT_TAG =~ /.*/'

release-lost_ds:
  stage: release-lost_ds
  script:
    - echo "" >> lost_ds/__init__.py
    - echo "__version__='${CI_COMMIT_TAG}'" >> lost_ds/__init__.py
    - sed -i 's/version="donotchange"/version="'"$CI_COMMIT_TAG"'"/' setup.py
    - pip install -U twine
    - python setup.py sdist bdist_wheel
    - twine upload dist/*
  only:
    - tags