[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lost_ds"
version = "donotchange"
description = "Lost Dataset library"
readme = "README.md"
license = {text="MIT"}
requires-python = ">=3.6"
authors = [
    {name="L3bm GmbH", email="info@l3bm.com"},
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
urls = {Repository = "https://github.com/l3p-cv/lost_ds"}
